#!/bin/sh

touch archive.tar.gz
touch archive.tgz
touch archive.tar.bz
touch archive.7z
touch archive.zip
touch archive.jar
touch sound.mp3
touch sound.wma
touch sound.wav
touch ms_office.xls
touch ms_office.xlsx
touch ms_office.ppt
touch ms_office.pptx
touch ms_office.doc
touch ms_office.docx
touch font.ttf
touch font.ttc
touch font.otf
touch image.bmp
touch image.gif
touch image.jpg
touch image.jpeg
touch image.png
touch image.tif
touch image.tiff
touch log_file.log
touch pdf_file.pdf
touch vector_image.svg
touch vector_image.eps
touch vector_image.ps
touch vector_image.ai
touch video.mkv
touch video.flv
touch video.avi
touch video.mov
touch video.wmv
touch video.mp4
touch video.mpg
touch video.webm
touch source.c
touch source.h
touch source.css
touch source.cpp
touch source.hpp
touch source.cc
touch source.hh
touch source.cxx
touch source.hxx
touch source.cs
touch source.go
touch source.html
touch source.xml
touch source.java
touch source.class
touch source.jl
touch source.js
touch source.md
touch source.m
touch source.nim
touch source.php
touch source.py
touch source.r
touch source.rb
touch source.sql
touch source.swift
touch source.tex
touch source.sty
touch source.ts
touch source.vim
touch Makefile

# Author: Tetsuya Ishikawa <tiskw111@gmail.com>
# vim: expandtab tabstop=4 shiftwidth=4 fdm=marker
