#!/bin/sh

rm -f archive.tar.gz
rm -f archive.tgz
rm -f archive.tar.bz
rm -f archive.7z
rm -f archive.zip
rm -f archive.jar
rm -f sound.mp3
rm -f sound.wma
rm -f sound.wav
rm -f ms_office.xls
rm -f ms_office.xlsx
rm -f ms_office.ppt
rm -f ms_office.pptx
rm -f ms_office.doc
rm -f ms_office.docx
rm -f font.ttf
rm -f font.ttc
rm -f font.otf
rm -f image.bmp
rm -f image.gif
rm -f image.jpg
rm -f image.jpeg
rm -f image.png
rm -f image.tif
rm -f image.tiff
rm -f log_file.log
rm -f pdf_file.pdf
rm -f vector_image.svg
rm -f vector_image.eps
rm -f vector_image.ps
rm -f vector_image.ai
rm -f video.mkv
rm -f video.flv
rm -f video.avi
rm -f video.mov
rm -f video.wmv
rm -f video.mp4
rm -f video.mpg
rm -f video.webm
rm -f source.c
rm -f source.h
rm -f source.css
rm -f source.cpp
rm -f source.hpp
rm -f source.cc
rm -f source.hh
rm -f source.cxx
rm -f source.hxx
rm -f source.cs
rm -f source.go
rm -f source.html
rm -f source.xml
rm -f source.java
rm -f source.class
rm -f source.jl
rm -f source.js
rm -f source.md
rm -f source.m
rm -f source.nim
rm -f source.php
rm -f source.py
rm -f source.r
rm -f source.rb
rm -f source.sql
rm -f source.swift
rm -f source.tex
rm -f source.sty
rm -f source.ts
rm -f source.vim
rm -f Makefile

# Author: Tetsuya Ishikawa <tiskw111@gmail.com>
# vim: expandtab tabstop=4 shiftwidth=4 fdm=marker
